### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by kabudu** [thephpleague/shunt#24]
@philsturgeon 

It's been nearly 3 years since the last commit on this project, and two issues I raised in December haven't had a response.

Can you please clarify the status of this project, as I may need to find an alternative if there is no longer support for this library.

Many thanks!

**Comment by philsturgeon** [comment]
Hey @kabudu! I raised this question with the project lead @toopay a few months back and was told he had "big plans" for a new version of it, but you're right, for now it does seem like it has been abandoned. 

I'll move it to the cemetery on the site so new folks dont come to it. It can always be revived later.

**Comment by kabudu** [comment]
@philsturgeon Thanks for the update! I'll keep an eye out for the latest and greatest! ;)
